Start
DOE-police/DOEDA pull request #1
Opened 2022-05-13 13:53 UTC by dmbarreiro

2022-05-13 13:57 UTC, ABohynDOE approved these changes

2022-05-13 13:57 UTC, ABohynDOE commented
Good job

2022-05-13 14:20 UTC, ABohynDOE commented
Here is an article that describes the regex we need to use for the DOI check: https://www.crossref.org/blog/dois-and-matching-regular-expressions/

2022-05-13 17:40 UTC, dmbarreiro commented
> Here is an article that describes the regex we need to use for the DOI check: https://www.crossref.org/blog/dois-and-matching-regular-expressions/

@ABohynDOE I adapted the regex using the one proposed by the article (adding the others brings little value and do not fully solves the problem, according to the article you would need dozens of regex to match all doi and you may still get some mismatches). 
You can have a look again and approve + merge if everything works for you. Let me know if you have more comments.

2022-05-13 20:31 UTC, ABohynDOE commented on utils/validation/scripts/validation.py
> +    for experiment in experiments_files:
So this validates all the files present in the experiment folder using `experiments.yaml` for the validation ?

2022-05-13 20:55 UTC, ABohynDOE requested changes
Since the format of the yaml files has changed, we must change the `validation.py` file.
Maybe we should first all agree on the format of the `.yml` files before implementing the changes ?

2022-05-14 10:45 UTC, dmbarreiro commented
> Since the format of the yaml files has changed, we must change the `validation.py` file. Maybe we should first all agree on the format of the `.yml` files before implementing the changes ?

Yeah, let's agree on the experiment schema before merging this

2022-05-18 09:13 UTC, ABohynDOE approved these changes

2022-05-19 08:21 UTC, ABohynDOE commented
We should adapt the regex of the name of the variables so that it takes symbols into account.
Ex. of string failing: 'Amonium Nitrate (%g)'

2022-05-19 08:27 UTC, ABohynDOE commented
We should have one file called `keywords.txt` where all the possible keywords are listed

2022-05-20 13:57 UTC, ABohynDOE commented
@dmbarreiro I think it's ready for merging

2022-05-20 13:58 UTC, ABohynDOE approved these changes

2022-05-20 13:58 UTC, merged